### PR TITLE
only embezzlers can be found lucky at the treasury, as it turns out

### LINKED ISSUE #1989: [BUG] Garbo nobarf target="sausage goblin" expecting sausage goblin and hitting embezzler
**Before Reporting**
Ensure that KoLMafia and garbo are both up to date before reporting a bug. If you have installed mafia in a weird or non-standard way, let us know any details about that here. But also, if you've installed mafia in a weird or non-standard way, I'm telling you right now that that's your bug. Also, check existing github issues to see if this has already been reported. If it has, consider leaving a comment with any additional information you can give on _that_ issue, instead of making a new one.

Also, read [this](BUGS.md).

**Describe the bug**
During chainStarters() when running target = "sausage goblin" it attempts to get lucky but is expecting a sausage goblin and hits an embezzler. Starts line 227
> Now running sausage goblin fight: Scepter Semirare. Stay tuned for details.

**To Reproduce**

1. Garbo nobarf target="sausage goblin" 
2. Wait until it starts trying Lucky adventures

**Expected behavior**
Should not abort, should start chaining the embezzlers I think? I dont know why it is looking for a sausage goblin during a lucky adventure.

**Session Log**
[sausage_gobbo.txt](https://github.com/user-attachments/files/16432290/sausage_gobbo.txt)

**Additional context**

### PR DESCRIPTION
**Pull request by horrible-little-slime**
Resolves #1989

### CODE REVIEW

File: packages/garbo/src/embezzler/fights.ts [hunk 1]
```diff
@@ -223,7 +223,8 @@ export const chainStarters = [
     "Scepter Semirare",
     () =>
       canAdventure($location`Cobb's Knob Treasury`) &&
-      shouldAugustCast($skill`Aug. 2nd: Find an Eleven-Leaf Clover Day`),
+      shouldAugustCast($skill`Aug. 2nd: Find an Eleven-Leaf Clover Day`) &&
+      globalOptions.target === $monster`Knob Goblin Embezzler`,
```
Comment (pstalcup) [inline packages/garbo/src/embezzler/fights.ts:227]: depending on how often we are doing this, it may be better to make something like `globalOptions.target === embezzler` or even `targetEmbezzlers()`. seems fine as is tho

**Review by pstalcup — APPROVED** [review]

File: packages/garbo/src/embezzler/fights.ts (hunk 1 above)
Comment (horrible-little-slime) [reply packages/garbo/src/embezzler/fights.ts:227]: Gonna merge as-is but probably do a `targetEmbezzlers` once we start doing things like removing robort prep and meat buffing
